PlayEv.WebUI/Models/GameModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PlayEv.WebUI.Models
{
    public class GameModel
    {

        [Required(ErrorMessage="Please enter the name of game")]
        [StringLength(50)]
        public string Name { get; set; }
        [Required(ErrorMessage="Write some description about the game")]
        [StringLength(250)]
        public string Description { get; set; }
        [Required(ErrorMessage="Specify game's category")]
        [StringLength(50)]
        public string Category { get; set; }
    }
}

PlayEv.WebUI/Models/UserLoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Security.Cryptography;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace PlayEv.WebUI.Models
{
    public class UserLoginViewModel
    {
        [Required]
        public string Username { get; set; }
        // MD5 encoded
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

PlayEv.WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PlayEv.Model.Abstract;
using PlayEv.Model.Concrete;
using PlayEv.Model.Entities;
using PlayEv.WebUI.Models;
using System.Text;
using System.IO;

namespace PlayEv.WebUI.Controllers
{
    public class GameController : Controller
    {
        private IGameRepository repository;

        public GameController()
        {
            repository = new EFGameRepository();
        }
        [Authorize]
        public ActionResult SubmitGame()
        {
            ViewBag.Category = repository.GetCategories();
            return View(new GameModel());
        }
        [Authorize]
        [HttpPost]
        public ActionResult SubmitGame(GameModel game, HttpPostedFileBase icon, HttpPostedFileBase sourceCode)
        {

            if (ModelState.IsValid)
            {
                if (icon != null && sourceCode != null)
                {
                    byte[] _icon = new byte[icon.ContentLength];
                    byte[] _sourceCode = new byte[sourceCode.ContentLength];
                    icon.InputStream.Read(_icon, 0, icon.ContentLength);
                    sourceCode.InputStream.Read(_sourceCode, 0, sourceCode.ContentLength);
                    repository.SubmitGame(new Game { Name = game.Name, Description = game.Description, Category = game.Category, Icon = _icon, SourceCode = _sourceCode });


                    return RedirectToAction("List");
                }
            }


            return View(game);
        }

        public ActionResult List()
        {
            return View(repository.Games);
        }
        [Authorize]
        public ActionResult Play(int game, string session)
        {
            ViewBag.GameId = game;
            ViewBag.GameSession = session;
            
            return View();
        }
        [Authorize]
        public ActionResult GameWindow(int gameId, string session)
        {
            ViewBag.GameId = gameId;
            ViewBag.GameTitle = repository.Games.FirstOrDefault(g => g.Id == gameId).Name;
            ViewBag.GameSession = session;
            return View();
        }
        [Authorize]
        public FileContentResult GameCode(int gameId)
        {
            Game game = repository.Games.FirstOrDefault(g => g.Id == gameId);
            if (game != null)
            {
                if (game.SourceCode != null)
                {
                    return File(game.SourceCode, "text/javascript");
                }
            }
                return null;
        }
    }
}

PlayEv.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlayEv.WebUI.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

PlayEv.WebUI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PlayEv.Model.Abstract;
using PlayEv.Model.Concrete;
using PlayEv.WebUI.Models;
using PlayEv.WebUI.Infrastructure.Abstract;
using System.Text;
using System.Security.Cryptography;
using System.Web.Security;
using System.Web.UI;
using PlayEv.Model.Entities;

namespace PlayEv.WebUI.Controllers
{
    public class UserController : Controller
    {
        private IUserRepository repository;
        private IAuthProvider authProvider;
        private ISecurePass passEncrypter;

        public UserController(IUserRepository repository, IAuthProvider authProvider, ISecurePass passEncrypter)
        {
            this.repository = repository;
            this.authProvider = authProvider;
            this.passEncrypter = passEncrypter;
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserLoginViewModel user)
        {
            if (ModelState.IsValid)
            {
                string encoded = passEncrypter.encriptPassword(user.Password);
                if (authProvider.Authenticate(user.Username, encoded, repository.Users.FirstOrDefault(u => u.Username == user.Username)))
                {
                    return RedirectToAction("Account");
                }
                else
                {
                    TempData["message"] = "Login failed";
                }
            }

            return View();
        }

        [Authorize]
        public ActionResult Account()
        {
            string username = User.Identity.Name.Split('|')[0];
            var user = repository.Users.FirstOrDefault(u => u.Username == username);
            user.Friends = repository.Friends(user.Id);
            return View(user);
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            return View(new UserLoginViewModel());
        }

        [HttpPost]
        public ActionResult Register(UserLoginViewModel user)
        {
            if (ModelState.IsValid)
            {
                var existing = repository.Users.FirstOrDefault(u => u.Username == user.Username);
                if (existing == null)
                {
                    repository.CreateUser(new User { Username = user.Username, Password = passEncrypter.encriptPassword(user.Password) });
                    return RedirectToAction("Account");
                }
                else
                {
                    ModelState.AddModelError("Error", "Username already takken");
                }
            }

            return View();
        }

        [Authorize]
        [ChildActionOnly]
        public ActionResult AddFriend()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddFriend(string username)
        {
            if (username != null)
            {
                if (!repository.AddFriend(int.Parse(User.Identity.Name.Split('|')[1]), username))
                {
                    ModelState.AddModelError("", "Username does not exist");
                }
            }
            else
            {
                ModelState.AddModelError("", "Username can not be empty");
            }

            return View();
        }

        [Authorize]
        public ActionResult RemoveFriend(int friendId)
        {
            repository.RemoveFriend(int.Parse(User.Identity.Name.Split('|')[1]), friendId);
            return View();
        }
    }
}

PlayEv.WebUI/Views/Game/GameWindow.cshtml
@{
    Layout = null;
}
<!DOCTYPE html/>
<html>
<head>
<title>Game</title>
    <script src="http://vivid-frost-4598.herokuapp.com/public/socket.io.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/pew.js")"></script>
    <script type="text/javascript">
        @{
            string username = User.Identity.Name.Split('|')[0];
            var application = ViewBag.gameTitle;
            var room = ViewBag.GameSession;
        }
        var username = "@username";
        var application = "@application";
        var room = @room;
    </script>
    <script type="text/javascript" src="@Url.Action("GameCode", "Game", new { gameId = ViewBag.GameId})">
    </script>
</head>
<body>
    <div id="container">
    </div>
</body>
</html>

PlayEv.WebUI/Views/Game/List.cshtml
@model IQueryable<PlayEv.Model.Entities.Game>
@{
    Layout = null;
}
@{
    foreach (var g in Model)
    {
    <div>
        <div>
            <h4>@g.Name</h4>
        </div>
        <div>@g.Description</div>
        <div>@g.Category</div>
        <div>@Html.ActionLink("Play", "Play", new { game = g.Id, session=  new Random().Next(1000)+""+g.Id})</div>
    </div>
    }
}

PlayEv.WebUI/Views/Game/Play.cshtml
<script src="http://vivid-frost-4598.herokuapp.com/public/socket.io.js"></script>
<script type="text/javascript" src="../../Scripts/pew.js"></script>
<script type="text/javascript" src="../../Content/Chat/ChatViewModel.js"></script>
<link rel="stylesheet" type="text/css" href="../../Content/Chat/Chat.css" />
<script type="text/javascript">
        @{
            string username = User.Identity.Name.Split('|')[0];
            var application = ViewBag.gameTitle;
            var room = ViewBag.GameSession;
        }
        var username = "@username";
        var application = "@application";
        var room = @room;
    </script>
<div class="game">
<h3>Game</h3>
    <iframe src="@Url.Action("GameWindow", new { gameId = ViewBag.GameId, session = ViewBag.GameSession })" width="600" height="400"  style="border:0px;">
    </iframe>
</div>

<div class="chat">
<h3>Chat</h3>
    <span data-bind="text: infoMessage"></span>
    <div id="messages" data-bind="text: messagesComputed" class="messages">
    </div>
    <!--<div data-bind="text: usersComputed" class="users">
    </div>-->
    <div style="clear: both"></div>
    <div class="controls">
        <input data-bind='value: message' placeholder="Enter your message" />
        <button data-bind="click: send">Send</button>
    </div>
</div>

PlayEv.WebUI/Views/Game/SubmitGame.cshtml
@model PlayEv.WebUI.Models.GameModel

@{
    ViewBag.Title = "SubmitGame";
}

<h2>SubmitGame</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


@using (Html.BeginForm("SubmitGame", "Game", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Game</legend>
        @Html.EditorForModel(Model)

        <input type="file" name="icon" />
        <input type="file" name="sourceCode" />
        <input type="submit" value="Submit" />
    </fieldset>
}

PlayEv.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@{
    Html.RenderAction("List", new { controller = "Game" });
}

PlayEv.WebUI/Views/Shared/ProfileSummary.cshtml
@{
    if (Request.IsAuthenticated)
    {
    <div>@User.Identity.Name.Split('|')[0] | @Html.RouteLink("Profile", new { controller = "User", action = "Account" }) | @Html.RouteLink("Log out", new { controller = "User", action = "LogOut" })</div>
    }
    else
    {
    <div>
        @Html.RouteLink("Register", new { controller = "User", action = "Register" }) |
        @Html.RouteLink("Login", new { controller = "User", action = "Login" })
    </div>
    }
}

PlayEv.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <script type="text/javascript" src="../../Scripts/knockout-2.0.0.js"></script>
    <link href="@Url.Content("~/Content/PlayEv.css")" rel="stylesheet" type="text/css" />
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")" rel="stylesheet" type="text/css" />
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Scripts/js")"></script>
</head>
<body>
    <div id="container">
        <div id="header">
            <div id="logo">
                <a href="@Url.RouteUrl(new { controller="Home", action="Index"})"><img src="@Url.Content("~/Content/images/logo.jpg")" alt="PlayEv" /></a></div>
            <div id="profile">
                @{
                    Html.RenderPartial("ProfileSummary");
                }
            </div>
            <div class="clearB">
            </div>
        </div>
        <div id="navigation">
            <div id="categories">
                <ul>
                    <li>Action</li>
                    <li>Gambling</li>
                    <li>Puzzle</li>
                </ul>
                <div class="clearB">
                </div>
            </div>
            <div id="search">
                <label>
                    Search:
                    <input type="search" /></label>
                <button>
                    Go</button>
            </div>
            <div class="clearB">
            </div>
        </div>
        <div id="content">
            @RenderBody()
        </div>
    </div>
</body>
</html>

PlayEv.WebUI/Views/User/Account.cshtml
@model PlayEv.Model.Entities.User

@{
    ViewBag.Title = "Account";
}
<h3>Account</h3>

<h4>Details</h4>
@Html.DisplayForModel(Model)

<h4>Friends</h4>

@{
    Html.RenderAction("AddFriend");
}

@{
    foreach (var u in Model.Friends)
    {
        <p><span>@u.Username</span><span>@Html.ActionLink("Remove", "RemoveFriend", new { friendId = u.Id})</span></p>
    }
}

PlayEv.WebUI/Views/User/AddFriend.cshtml
@{
    Layout = null;
    using(Html.BeginForm()){
        <input type="text" value="" name="username"/>
    <input type="submit" value="Add" />
    }
}

PlayEv.WebUI/Views/User/Login.cshtml
@model PlayEv.WebUI.Models.UserLoginViewModel

@{
    ViewBag.Title = "Login";
}
@{
    var message = TempData["message"];
    if(message != null){
        <div>@message</div>
    }
}
<h3>Login</h3>
@using (Html.BeginForm())
{
    @Html.EditorForModel(Model)
    <input type="submit" value="Login" />
}

PlayEv.WebUI/Views/User/Register.cshtml
@model PlayEv.WebUI.Models.UserLoginViewModel

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>
<div class="ErrorMessage">
@Html.ValidationSummary()
</div>
@using(Html.BeginForm()){
    <label>Nickname: @Html.EditorFor(m => m.Username)</label><br />
    <label>Password: @Html.EditorFor(m => m.Password)</label><br />
    <input type="submit" value="Register" />
}

PlayEv.WebUI/Views/User/RemoveFriend.cshtml
@{
    ViewBag.Title = "RemoveFriend";
}

<h2>Friend removed</h2>